services:
  api:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"

  db:
    image: mysql:latest
    restart: always 
    environment: 
      MYSQL_DATABASE: 'mysql_db'
      MYSQL_USER: 'mysql_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - '8080:8080'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'password'


volumes:
  mysql-db:
